version: '3.8'

services:
  grafana:
    environment:
      - GF_SERVER_ROOT_URL=http://${PUBLIC_IP}:3000
      - GF_SERVER_SERVE_FROM_SUB_PATH=false
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_USERS_ALLOW_ORG_CREATE=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer

  prometheus:
    environment:
      - PROMETHEUS_EXTERNAL_URL=http://${PUBLIC_IP}:9090
